### ISSUE TITLE
Plugin for GoGS / Gitea

### ISSUE THREAD

**Issue by hamidfzm** [getsentry/sentry-plugins#145]
Since [GoGS](https://gogs.io/) is a self hosted git service (like sentry which is self hosted too) and can be used with an external issue tracker it would be a good idea to add a plugin for it.

Also GoGs has Restful API service, so i think it would be easy to implement a plugin for GoGS.

**Comment by hollowimage** [comment]
+1 on the idea as well.

**Comment by stygmate** [comment]
+1

**Comment by linkinkov** [comment]
+1

**Comment by nephthys** [comment]
+1 too

**Comment by rakshith-ravi** [comment]
@hamidfzm do we have any progress on this?

**Comment by Selnapenek** [comment]
+1

**Comment by willvincent** [comment]
+1 Also the more feature-rich fork, please... Gitea :)

**Comment by MrMoronIV** [comment]
Would like to see a connection with Gitea as well!

**Comment by alexanderadam** [comment]
@hamidfzm could you please add Gitea to the title as well (i.e. `Plugin for GoGS / Gitea`)?

### For the person who might want to implement this

#### Gitea vs GoGS API

[**Gitea**](https://github.com/go-gitea/gitea/) is a fork of [**GoGS**](https://github.com/gogs/gogs) that has nowadays nearly 3'000 patches on top of Gogs and more maintainers, more functionality and bugs fixed that are still in GoGS (that's the reason why I switched once). So if you are running in some API bug, you should keep that in mind.

#### Testing against an API

Also you can simply test the API integration on [the _official test instance_ at `https://try.gitea.io/`](https://try.gitea.io/). There you can also find [the _Swagger API_ definition](https://try.gitea.io/api/swagger). As you can see, JSON and HTTP are protocol wise the only requirements.
If you rather want to use a _local_ Gitea instance, you might want to use [the official _Docker image_](https://hub.docker.com/r/gitea/gitea/) (there's also an example [`docker-compose.yml`](https://hub.docker.com/r/gitea/gitea/#quick-set-up)).

There's also more on [API authorisation in the documentation](https://docs.gitea.io/en-us/api-usage/).

I hope this helps.

PS: Also keep in mind that this might be a good project for [Hacktoberfest](https://hacktoberfest.digitalocean.com/). :wink:

**Comment by hamidfzm** [comment]
@alexanderadam Done :)

**Comment by AienTech** [comment]
@hamidfzm is it now installable or configurable with an on-premise version?

**Comment by alexanderadam** [comment]
@AienTech Hamid is the one who opened this issue and he answered me because I asked him to add Gitea to the topic of this issue.
So in case you thought that this **issue** is is done: **this is not the case**. :wink: 

To make this clear: the development of Sentry and it's plugins in general is _very_ slow. :turtle: Indeed _so_ slow that [someone made a PR for adding a Redmine plugin in 2016(!)](https://github.com/getsentry/sentry-plugins/pull/112) and until now he didn't even got a _Response_ (except for the Travis issue). :snail: 

I don't want to crush any dreams here but I don't think this issue will be solved in the next few years. I just wanted to add the information so that it is clear that there's everything available if someone is _considering_ in adding Gitea functionality.

PS: This comment is just for putting the current state in a realistic light and _not_ for offending someone. I want to be clear here that I think that the Sentry team is doing a _great_ job in general. I guess there's simply not enough time and workforce available to tackle all open PRs and issues.

**Comment by BYK** [comment]
Closing as this repo is now deprecated and merged into getsentry/sentry. Feel free to submit a PR there if you are interested in implementing this.
