### ISSUE TITLE
Use the share url instead of the private sentry issue URL when creating github issues

### ISSUE THREAD

**Issue by noirbizarre** [getsentry/sentry-plugins#303]
Hi!

Most of the time, Sentry is an internal tools whereas github issues are public. It think it would be better to use the the share URL instead or the issue URL when creating github issues (or at least give the choice somewhere).

**Comment by mattrobenolt** [comment]
I don't think we should do this by default since there are many cases where you may use a public issue tracker, but that doesn't mean you want to actually share the link publicly. If anything, I think we could do like, "If issue is shared, grab the shared url, if not, use the private one". But I don't think we should automatically generate a share url just because you create an issue.

Is that what you were intending?

**Comment by noirbizarre** [comment]
Almost:
Right now, if I create a github issue which is public (most of the time this is the case with open sources projects), the created issue publish the private URL and this doesn't allow the bugfixer to read the sentry report. I believe publishing the the private URL only makes sense if the github project is also a private one.
So to me the algorythm should be: "If the github repository I create the issue on is public then share the sentry issue and use the public link"
The fact the issue will be shared can be warned on the issue creation modal.

Another alternative can be a global parameter or a team/organisation parameter.

Right now, I don't/can't use this feature, I perform the whole workflow manually:
- generate the share link
- manually create an issue on github with a reference to the share url
- go back on sentry and attach the created issue
Honnestly, when I have a lot of issue, I stop it pretty quickly

It's sad because sentry input is valuable for bugfixers, ahd the share screen is great: external contributors can read the stack trace without any personnal or critical data, team members have a link to the detailed issue.
