### ISSUE TITLE
Support self-signed certificate on GitLab

### ISSUE THREAD

**Issue by skywatch-jtv** [getsentry/sentry-plugins#348]
I'm using a self-signed certificate on the GilLab server, which causes an error in the GitLab integration:

```
HTTPSConnectionPool(host='****', port=443): Max retries exceeded with url: /api/v3/projects/test%2Fembedded-playground (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

I've tried installing the certificate as a root cert in the sentry docker image, but to no avail :-(

Are there any posibility to disable certificate verification, or where/how should the cert be installed?

**Comment by chanyying** [comment]
@skywatch-jtv 
Hello, Can ` HTTPConnectionPool ` be used normally? I have such a problem.

```
ConnectTimeout: HTTPConnectionPool(host='git.xxx.com', port=80): Max retries exceeded with url: /api/v3/projects/frontend%2Fsem (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa894496dd0>, 'Connection to git.xxx.com timed out. (connect timeout=30)'))
13:52:24 [ERROR] sentry.plugins.gitlab: HTTPConnectionPool(host='git.xxx.com', port=80): Max retries exceeded with url: /api/v3/projects/frontend%2Fsems (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa894496dd0>, 'Connection to git.xxx.com timed out. (connect timeout=30)'))
```

**Comment by Scherer81** [comment]
Same issue here.

Attempts through HTTP/HTTPS isn't working.

Is there any fix and/or workaround?

**Comment by JakeDEvans** [comment]
bump

**Comment by chanyying** [comment]
After trying the upgrade, it's ready to use

**Comment by daneb5** [comment]
bump

**Comment by Jakst3r** [comment]
Bump

**Comment by JakeDEvans** [comment]
@BYK closed fixed? or just Don't Care/Won't Fix

**Comment by BYK** [comment]
Closed due to staleness, this repo being deprecated, and this issue unlikely to be addressed, at least here in this repo or over at getsentry/sentry. I think this may be resolved with some tweaks in the Docker image by adding the self-signing CA to the OS trust list but it may be a better alternative to use Let's Encrypt.

In any case, if you want to keep discussing I recommend using [the forums](https://forum.sentry.io) until there's a clear path for a code fix in getsentry/sentry.
