### ISSUE TITLE
Slack notification theme color is too vivid

### ISSUE THREAD

**Issue by azihsoyn** [getsentry/sentry-plugins#353]
Hi, I am using sentry and slack integration.
It is very useful, but sometime notification color is too powerful.

If environment is staging, or log level is info or warning, color is already red.

Do you have plan to customizeable notification color ?

Thanks.

**Comment by blairanderson** [comment]
I would also like to see something fixed here. 

the **resolved** coloring should be significantly different than the **unresolved**. 

![image](https://user-images.githubusercontent.com/955736/50528724-da9ac080-0aa4-11e9-9502-8a8d69e1fb20.png)

**Things most users expect to see:**

1. use GREEN instead of GREY for resolved tasks
1. change the LOGO color on resolved tasks 

**Notice how GitHub does this**:

GREEN

![sentry-github-green](https://user-images.githubusercontent.com/955736/50528815-6876ab80-0aa5-11e9-8655-a6947d7fd050.jpg)


RED
![sentry-github](https://user-images.githubusercontent.com/955736/50528803-5dbc1680-0aa5-11e9-9a63-ab3c8c54ed34.jpg)
