### ISSUE TITLE
Sentry - JIRA Add Labels field to default JIRA settings

### ISSUE THREAD

**Issue by dhoomakethu** [getsentry/sentry-plugins#358]
Version: 8.22.0
We are using JIRA integration with our sentry and have enabled automatic creation of JIRA tickets. However , we would like to have the ability to add default labels per project so that it would be easier to track the tickets on JIRA which are created by sentry. This ability to add labels to JIRA ticket is available when manually creating the JIRA .

**Comment by CliffCawley** [comment]
This would be great, and just to add to this, would be great to optionally either prepend or append text to the summary.

I.e. I'd love to prepend '[Sentry] ' or something else.

If you could provide both labels and this, then I'd be happy!

**Comment by guptameet** [comment]
Was googling to find out a way to add labels to the issues and found this. 

Need this for managing issues project-wise.

**Comment by simonweil** [comment]
Adding default labels would be very helpful!

**Comment by jpmgoncalves** [comment]
I need this on a daily basis. Would love to see this feature added to Sentry's JIRA integration.

**Comment by snalwani** [comment]
+1, Default labeling/ Prefixing on the title would be really helpful in managing sentry related Jira tickets.

**Comment by ceorourke** [comment]
We're not prioritizing changes to the Jira plugin since we've released the newer global Jira integration.  This integration now allows you to set a "default" label. Per project, we'll store the last value entered into a Jira ticket's label field i.e. you open up a Sentry issue, create a Jira ticket and enter "sentry" as the label, and then the next time you create a Jira ticket in Sentry that field will already be filled in. Setup documentation for the newer integration can be found [here](https://docs.sentry.io/workflow/integrations/global-integrations/jira/) and the PR for this change can be found [here](https://github.com/getsentry/sentry/pull/12874).
