### ISSUE TITLE
[JIRA] Filter new issues by alert rules 

### ISSUE THREAD

**Issue by wangjoshuah** [getsentry/sentry-plugins#364]
Allow rules to apply to when the JIRA integration creates a new issue. 

For example:
I do not want all issues in sentry to create an issue in JIRA. I ONLY want issues in my production environment to automatically create issues in JIRA.

**Comment by SolonHUG** [comment]
Hi,
I encounter exactly the same issue. I have a local sentry server (9.0.0) where I configured both Slack and Jira integrations. Slack notifications works well, and I'm able to trigger notifications depending on different alert rules : send notification via slack, send notification for legacy integrations, custom tag value matching, etc...
HOWEVER, regarding JIRA, I see the following : 
- when I check the 'Automatically create a JIRA ticket for EVERY new issue' in the plugin configuration, it works well, and a JIRA issue is correctly created for every new Sentry event (and linked accordingly)
- but when I uncheck the flag, I am not able to trigger creation of Jira issues anymore, whatever the alert rule is (whereas I know the rule is executed because it generates slack notifications correctly)

What is the correct way to to generate JIRA tickets according to alert rules criteria ? Is it normal that unckecking 'Automatically create JIRA Tickets' in the Jira plugin completly disables the creation of Jira issues ?

Thanks
 

-

**Comment by YashishDua** [comment]
@wangjoshuah I am facing the same issue.
