### ISSUE TITLE
Unable to configure GitHub integration / associate identity

### ISSUE THREAD

**Issue by hollodotme** [getsentry/sentry-plugins#449]
## Sentry infos

* Version: `9.0.0`
* onpremise docker-compose setup using official docker-sentry image
* nginx with SSL in front of sentry
* SENTRY_URL_PREFIX: `https://sentry.company.tld`

## Steps taken

1. Created a [GitHub oauth application](https://github.com/settings/applications/)
2. Set homepage URL to `https://sentry.company.tld`
3. Set authorization callback URL to `https://sentry.company.tld` or `https://sentry.company.tld/account/settings/social/associate/complete/github/` (both do not work) - Considered #284
4. Set the following environment variables 
    * `GITHUB_APP_ID: <Client ID from GitHub oauth application>`
    * `GITHUB_API_SECRET: <Client Secret from GitHub oauth application>`
    * `SOCIAL_AUTH_REDIRECT_IS_HTTPS: 'True'`
    * `SECURE_PROXY_SSL_HEADER: ('HTTP_X_FORWARDED_PROTO', 'https')`
    * `USE_X_FORWARDED_HOST: 'True'`
5. Try to add a repository at `https://sentry.company.tld/organizations/myorg/repos/` and getting this dialog: 
<img width="615" alt="screenshot 2019-03-01 at 13 28 49" src="https://user-images.githubusercontent.com/1557839/53638253-fb5ad000-3c25-11e9-826d-27a959885a7b.png">
6. Clicking on "Associate Identity" always results in not associating an identity:

* It shows the sentry startpage if I set `https://sentry.company.tld` as the authorization callback URL in the GitHub oauth application

* It shows the following error if I set `https://sentry.company.tld/account/settings/social/associate/complete/github/` as the authorization callback URL in the GitHub oauth application:
  <img width="733" alt="screenshot 2019-03-01 at 13 32 45" src="https://user-images.githubusercontent.com/1557839/53638436-863bca80-3c26-11e9-9867-58c6be6617df.png">

---

And I'm also seeing the "Wrong Backend" error in the internal error list, that is reported in #284. 

<img width="1070" alt="screenshot 2019-03-01 at 13 44 45" src="https://user-images.githubusercontent.com/1557839/53639001-4970d300-3c28-11e9-93e6-df74fa33188a.png">

---

Is one of the steps wrong or am I missing something? Any help is much appreciated!
Thanks.

**Comment by ellisvlad** [comment]
Experiencing same issue, I have SSO working by using https://sentry.company.tld/auth/sso/ as the Github app's Authorization callback URL. But cannot "associate identity" / add repository in sentry. I'll add some extra details I've found when trying to debug this myself:

Logging shows that in step 5, the dialog appears because `https://sentry.company.tld/api/0/organizations/company/repos/` is responding with {"error_type": "auth", "auth_url": "/account/settings/social/associate/github/"}.

Step 6 Shows that the client's browser is directed to https://sentry.company.tld/account/settings/social/associate/github/?next=%2Fsettings%2Fcompany%2Frepos%2F which redirects to GitHub OAuth authorize with a redirect_uri set to https://sentry.company.tld/account/settings/social/associate/complete/github/?redirect_state=xxxxxxxxxx . Though GitHub instead redirects to the GitHub App's Authorization callback URL with an error and error description set "error_description: The redirect_uri MUST match the registered callback URL for this application."

**Comment by richvdh** [comment]
likewise here.

**Comment by BYK** [comment]
This repo is deprecated and merged into getsentry/sentry. I think https://github.com/getsentry/sentry/issues/12670 is a better place to keep discussing this.
