### ISSUE TITLE
Proposal: Include Environment and Project name in pagerduty incident description

### ISSUE THREAD

**Issue by dpritchett** [getsentry/sentry-plugins#543]
Hi there! I've been getting non-urgent pages lately of the "let's not let this go unnoticed" kind and I'd really like to be able to tell before clicking through from slack to PD to Sentry that a page relates to project X or environment Y.

**Relevant code**: the `description` method in [PagerDutyClient](https://github.com/getsentry/sentry-plugins/blob/03de8c0c085f4df93dff83a946c77499aae57ba0/src/sentry_plugins/pagerduty/client.py#L41).

![image](https://user-images.githubusercontent.com/147981/68892739-400d9500-06e9-11ea-84b4-c458f21ac658.png)

I'm pretty sure I could hack that out (with a test!) in less than a day but I didn't want to do so without getting a provisional 👍 from someone at Sentry with merging powers. Looks like most of the fingerprints on this module are from @dcramer, so hi! 👋

## Current UX
![image](https://user-images.githubusercontent.com/147981/68892200-0be5a480-06e8-11ea-8b4a-c15eca6a5f18.png)
Scary! Is the sky falling? 😱 

## Mocked-up proposed UX
![image](https://user-images.githubusercontent.com/147981/68892330-5cf59880-06e8-11ea-9034-fe12425290b2.png)
Not scary! Deep breath, back to work. Maybe let someone know they triggered an alert. ☺️

**Comment by dpritchett** [comment]
n.b. I would've come to you with working code and a test already but I bailed after the 3rd or 4th time I got stuck installing this project and the companion project (largely self-inflicted issues I'm sure 🤣 ). I'm sure I could pull it off, but I don't wanna go too deep without some 👀 .

**Comment by manuzope** [comment]
Hey @dpritchett! Thanks for posting!

Changing the `description` is a pretty wide-reaching change, which I don't feel everyone would want as it does crowd out the error description.

What do you think of this workflow instead:
* Only send events from the prod environment to PagerDuty
* Send non-prod events to Slack directly from Sentry? When you do this, you can also ask our integration to explicitly mention the environment in the message.

**Comment by dpritchett** [comment]
Agreed on all counts! I wouldn't want to force a cascading re-definition of the purpose of `definition` across the domain model.

My real ask is "is it possible to add more info to the one-liners that pop up on my phone/SMS/email when I get paged so that I can better triage them before jacking in to my console and getting to work?"

I recognize that this may be a "you're using sentry/PagerDuty wrong" smell more than a "missing feature in this module" scenario and I'd appreciate any suggestions you could offer in either direction.

_RE: your two suggestions above:_

Are these both possible as-is? I'd definitely like to try them out if so.

Thanks!

**Comment by manuzope** [comment]
Yes, you can do those today!

Follow these steps:
* Add the slack integration by going to https://sentry.io/settings/<org_slug>/integrations/
* Edit the PagerDuty alert so that only prod goes to it here: https://sentry.io/settings/<org_slug>/projects/<project_slug>/alerts/rules/
* Create a new alert rule so that other environments only go to slack. Should look something like this:
![New_Alert_Rule_-_backend_-_Sentry](https://user-images.githubusercontent.com/1417849/69273098-a2084780-0b8c-11ea-91b9-9a3052f4826f.png)

> My real ask is "is it possible to add more info to the one-liners that pop up on my phone/SMS/email when I get paged so that I can better triage them before jacking in to my console and getting to work?"

If you want to include other details in your PagerDuty description (which would then change the message you see in your PD notifications), that's going to be hard. Maybe in the future you could use PagerDuty's [event rules](https://support.pagerduty.com/docs/global-event-rules) to augment the description. That is, however, not possible today cause the sentry integration sends it to their [old endpoint](https://github.com/getsentry/sentry-plugins/blob/03de8c0c085f4df93dff83a946c77499aae57ba0/src/sentry_plugins/pagerduty/client.py#L7), with which I don't think event rules work. We are working on a new PagerDuty integration that will make that possible. I can tell you about that when it's in beta, if you'd like.

If you just want it in Slack, I think the steps above might work.

**Comment by BYK** [comment]
Since this repo is now deprecated and the plugins now live in getsentry/sentry, I'm closing the issue.

Feel free to open a new issue (or a PR) over there and continue the conversation.
