### ISSUE TITLE
Issue installing and running v8.10.0

### ISSUE THREAD

**Issue by sandipagarwal** [getsentry/sentry-plugins#89]
My team is facing a weird issue when installing and running sentry-plugins v8.10.0 (latest as of date).

The following steps run fine:
1. pip install sentry-plugins
2. sentry upgrade

Problem occurs when we run the services. Debugging further we found the following problem:
![sentryerror](https://cloud.githubusercontent.com/assets/988003/20516438/9230a312-b0bc-11e6-9698-85ab4d78fedb.png)

We tried debugging and find the source code. But, all looks fine to us. Are we missing something?

P.S.: Sentry v8.9.0 used.

**Comment by mattrobenolt** [comment]
Sentry server 8.10 is required. The versions must match.

**Comment by sandipagarwal** [comment]
@mattrobenolt As far as is seen here(https://github.com/getsentry/sentry-plugins/blob/master/setup.py#L28), the sentry version needs to be fixed accordingly.

**Comment by mattrobenolt** [comment]
@sandipagarwal that's explicitly under `tests_requires`. There is no hard install requirement enforced by setup.py.

**Comment by sandipagarwal** [comment]
@mattrobenolt I understand. But, it would be great and safe if we update it to `'sentry>=8.10.0'`. I had 8.9 installed prior to using sentry-plugins. So, installing sentry-plugins didn't change the sentry installation. Hence, I never could realize that it could be a problem. Now, upgrading after you mentioning it made my work done in not more than 2 min.

**Comment by mattrobenolt** [comment]
There are reasons why we explicitly don't do that. 

Sentry the server is much more complicated and much more sensitive than the plugins. Unintentionally upgrading the server could have negative consequences if you weren't paying attention. So someone comes alone and things, "hey, let see upgrade our plugins to get this hot new feature" and next thing they know, sentry the server also gets upgraded without them knowing. 

Instead of coupling things closely like that, I've chosen to loosely couple, but coordinate versions and releases to coincide with each other. So just simply make sure your versions match and all will be good.

To be fair though, we definitely need to update documentation and whatnot to explain this process better.

**Comment by sandipagarwal** [comment]
Thanks @mattrobenolt,
That makes perfect sense. Would look forward for the change in the documentation.
